version: "3.8"

services:
  frontend:
    image: khunlook-client-side:1
    build:
      context: .
      args:
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: client-side
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - khunlook

networks:
  khunlook:
    driver: bridge
    name: khunlook
